use_sim_time: True

amcl:
  ros__parameters:
    use_map_topic: false   # only used if you switch to AMCL + saved map

bt_navigator:
  ros__parameters:
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]

recoveries_server: {ros__parameters: {}}
smoother_server:   {ros__parameters: {}}
waypoint_follower: {ros__parameters: {}}

