<?xml version="1.0"?>
<robot name="mm_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_separation" value="0.34"/>

  <!-- Base -->
  <link name="base_link">
    <inertial>
      <mass value="8.0"/>
      <origin xyz="0 0 0.05"/>
      <inertia ixx="0.2" iyy="0.2" izz="0.2" ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual><origin xyz="0 0 0.05"/><geometry><box size="0.4 0.3 0.1"/></geometry></visual>
    <collision><origin xyz="0 0 0.05"/><geometry><box size="0.4 0.3 0.1"/></geometry></collision>
  </link>

  <!-- Left wheel -->
  <link name="left_wheel">
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0006" iyy="0.0006" izz="0.0012" ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual><geometry><cylinder radius="${wheel_radius}" length="0.05"/></geometry></visual>
    <collision><geometry><cylinder radius="${wheel_radius}" length="0.05"/></geometry></collision>
  </link>
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_separation/2} 0.05" rpy="0 1.57079632679 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Right wheel -->
  <link name="right_wheel">
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0006" iyy="0.0006" izz="0.0012" ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual><geometry><cylinder radius="${wheel_radius}" length="0.05"/></geometry></visual>
    <collision><geometry><cylinder radius="${wheel_radius}" length="0.05"/></geometry></collision>
  </link>
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 -${wheel_separation/2} 0.05" rpy="0 1.57079632679 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Top plate -->
  <link name="top_plate">
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.002" iyy="0.002" izz="0.002" ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual><origin xyz="0 0 0.18"/><geometry><box size="0.28 0.22 0.02"/></geometry></visual>
    <collision><origin xyz="0 0 0.18"/><geometry><box size="0.28 0.22 0.02"/></geometry></collision>
  </link>
  <joint name="top_plate_joint" type="fixed">
    <parent link="base_link"/>
    <child link="top_plate"/>
  </joint>
</robot>

