arm_controller:
  ros__parameters:
    joints:
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint
    command_interfaces: [position]
    state_interfaces:   [position, velocity]
    allow_partial_joints_goal: true
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01
