controller_manager:
  ros__parameters:
    update_rate: 200
    use_sim_time: true

    # Register controllers + their types (types ONLY go here)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    base_controller:
      type: diff_drive_controller/DiffDriveController
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# --- Per-controller parameters (live at top level) ---

joint_state_broadcaster:
  ros__parameters: {}

base_controller:
  ros__parameters:
    left_wheel_names:  ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_radius: 0.05
    wheel_separation: 0.34
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    enable_odom_tf: true

arm_controller:
  ros__parameters:
    joints:
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_nonzero_velocity_at_trajectory_end: true

