wheel_vel_test:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - left_wheel_joint
      - right_wheel_joint
    command_interfaces: [velocity]
    state_interfaces:   [velocity]